// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGu3NSJRt_PF9yddAbn1PjU1g8xMXvmrY',
    appId: '1:582565721581:web:06c2d0befc9ebf4f0e63e4',
    messagingSenderId: '582565721581',
    projectId: 'authenticationp-688a8',
    authDomain: 'authenticationp-688a8.firebaseapp.com',
    storageBucket: 'authenticationp-688a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDULVSroUukilfEcFF2_nTyRp-z3hoA9TM',
    appId: '1:582565721581:android:08f8a234d356e34d0e63e4',
    messagingSenderId: '582565721581',
    projectId: 'authenticationp-688a8',
    storageBucket: 'authenticationp-688a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChbbyMxRy16o_afPiRyW13B1LM_qC-IXU',
    appId: '1:582565721581:ios:8121c6a04229f61a0e63e4',
    messagingSenderId: '582565721581',
    projectId: 'authenticationp-688a8',
    storageBucket: 'authenticationp-688a8.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChbbyMxRy16o_afPiRyW13B1LM_qC-IXU',
    appId: '1:582565721581:ios:8121c6a04229f61a0e63e4',
    messagingSenderId: '582565721581',
    projectId: 'authenticationp-688a8',
    storageBucket: 'authenticationp-688a8.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGu3NSJRt_PF9yddAbn1PjU1g8xMXvmrY',
    appId: '1:582565721581:web:a0b8e0aefce726dd0e63e4',
    messagingSenderId: '582565721581',
    projectId: 'authenticationp-688a8',
    authDomain: 'authenticationp-688a8.firebaseapp.com',
    storageBucket: 'authenticationp-688a8.firebasestorage.app',
  );
}
