// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBugiWptGrixvO9uGIxyBug2XYbioW6na0',
    appId: '1:691245817056:web:5156e8736942c0406e8485',
    messagingSenderId: '691245817056',
    projectId: 'fir-auth-demo-b2edf',
    authDomain: 'fir-auth-demo-b2edf.firebaseapp.com',
    storageBucket: 'fir-auth-demo-b2edf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAJXEUuWm31L68twRgz6ITM1gALljSYhk',
    appId: '1:691245817056:android:62fe83dfea51d07b6e8485',
    messagingSenderId: '691245817056',
    projectId: 'fir-auth-demo-b2edf',
    storageBucket: 'fir-auth-demo-b2edf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf7by0lGMfRvX6iqggQdV0_yfqaBjHdnU',
    appId: '1:691245817056:ios:9d283a028c6518636e8485',
    messagingSenderId: '691245817056',
    projectId: 'fir-auth-demo-b2edf',
    storageBucket: 'fir-auth-demo-b2edf.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf7by0lGMfRvX6iqggQdV0_yfqaBjHdnU',
    appId: '1:691245817056:ios:9d283a028c6518636e8485',
    messagingSenderId: '691245817056',
    projectId: 'fir-auth-demo-b2edf',
    storageBucket: 'fir-auth-demo-b2edf.firebasestorage.app',
    iosBundleId: 'com.example.firebaseAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBugiWptGrixvO9uGIxyBug2XYbioW6na0',
    appId: '1:691245817056:web:47cba30b5518c4066e8485',
    messagingSenderId: '691245817056',
    projectId: 'fir-auth-demo-b2edf',
    authDomain: 'fir-auth-demo-b2edf.firebaseapp.com',
    storageBucket: 'fir-auth-demo-b2edf.firebasestorage.app',
  );
}
