// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbVv6AgxqC3lnlot7FDFoNmovwXWV0tG4',
    appId: '1:873346182887:web:ba8d2ec19c378e3c73fc42',
    messagingSenderId: '873346182887',
    projectId: 'first-backend-101',
    authDomain: 'first-backend-101.firebaseapp.com',
    storageBucket: 'first-backend-101.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjSdB11rIbh4J10rX_2CKH5M-t77yWUuc',
    appId: '1:873346182887:android:5b118cecc160696273fc42',
    messagingSenderId: '873346182887',
    projectId: 'first-backend-101',
    storageBucket: 'first-backend-101.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhkb75h-Dz1bO01ujxdel_FEG4nLYiPnw',
    appId: '1:873346182887:ios:5ede74016ac9271173fc42',
    messagingSenderId: '873346182887',
    projectId: 'first-backend-101',
    storageBucket: 'first-backend-101.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhkb75h-Dz1bO01ujxdel_FEG4nLYiPnw',
    appId: '1:873346182887:ios:5ede74016ac9271173fc42',
    messagingSenderId: '873346182887',
    projectId: 'first-backend-101',
    storageBucket: 'first-backend-101.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbVv6AgxqC3lnlot7FDFoNmovwXWV0tG4',
    appId: '1:873346182887:web:b40007bf666c939173fc42',
    messagingSenderId: '873346182887',
    projectId: 'first-backend-101',
    authDomain: 'first-backend-101.firebaseapp.com',
    storageBucket: 'first-backend-101.firebasestorage.app',
  );
}
